- .github/workflows/dotnet.yml
- PolySharp.sln
- README.md
- src/PolySharp.SourceGenerators/Extensions/AnalyzerConfigOptionsProviderExtensions.cs
- src/PolySharp.SourceGenerators/PolySharp.targets
- src/PolySharp.SourceGenerators/PolyfillsGenerator.cs
- tests/PolySharp.NuGet/PolySharp.NuGet.csproj
- tests/PolySharp.Tests/PolySharp.Tests.csproj
This PR adds the `PolySharpUsePublicAccessibilityForGeneratedTypes` option to generate polyfills as public types.
> Add PolySharpUsePublicAccessibilityForGeneratedTypes option

- README.md
- src/PolySharp.SourceGenerators/Models/GenerationOptions.cs
- src/PolySharp.SourceGenerators/PolySharp.targets
- src/PolySharp.SourceGenerators/PolyfillsGenerator.Execute.cs
- src/PolySharp.SourceGenerators/PolyfillsGenerator.cs
This PR adds a new "PolySharpIncludeGeneratedTypes" option to allow generation only for specific types.
> Add PolySharpIncludeGeneratedTypes MSBuild option

- PolySharp.sln
- src/PolySharp.SourceGenerators/AnalyzerReleases.Shipped.md
- src/PolySharp.SourceGenerators/Diagnostics/Analyzers/UnsupportedCSharpLanguageVersionAnalyzer.Execute.cs
- src/PolySharp.SourceGenerators/Diagnostics/Analyzers/UnsupportedCSharpLanguageVersionAnalyzer.cs
- src/PolySharp.SourceGenerators/Diagnostics/DiagnosticDescriptors.cs
- src/PolySharp.SourceGenerators/EmbeddedResources/System.Runtime.CompilerServices.CompilerFeatureRequiredAttribute.cs
- src/PolySharp.SourceGenerators/Extensions/CompilationExtensions.cs
- src/PolySharp.SourceGenerators/PolyfillsGenerator.Execute.cs
- src/PolySharp.SourceGenerators/PolyfillsGenerator.cs
- tests/PolySharp.MinimumCSharpVersion.Tests/PolySharp.MinimumCSharpVersion.Tests.csproj
This PR does two things:
- Ensures all polyfills build with C# 8.0
- Skips polyfills with C# < 8.0 and emits a warning instead
> Handle C# 8.0 as minimum version

- Directory.Build.props
- src/Directory.Build.props
Needs a bump in nugetizer for the compatible property to work (used to require IsDevelopmentDependency).
Fixes #19
> Make package a development dependency

- src/PolySharp.SourceGenerators/PolySharp.targets
This PR fixes support for multiline properties, which don't normally work out of the box due to a Roslyn limitation.
> Fix multiline properties for generator

- src/PolySharp.SourceGenerators/Models/GeneratedType.cs
- src/PolySharp.SourceGenerators/Models/SyntaxFixupType.cs
- src/PolySharp.SourceGenerators/PolyfillsGenerator.Execute.cs
- tests/PolySharp.NuGet/PolySharp.NuGet.csproj
This PR adds a couple workarounds to also support .NET 3.5:
- Strip the `[MethodImpl]` attributes when the target option isn't present
- Skip generating `System.Range` if `System.ValueTuple`2` isn't present
> Add workarounds to support .NET 3.5

- src/PolySharp.Package/PolySharp.Package.msbuildproj
This PR fixes the README.md file being packed twice when creating the NuGet package.
> Fix README.md being packed twice

- src/PolySharp.SourceGenerators/PolySharp.targets
Clarify that .NET SDK 6.0.400, which which shipped with VS 17.3, is the minimum SDK.
E.g. 6.0.302 does not not work even though ".NET 6 SDK or greater" might make you think so.
> Specify the minimum .NET 6 SDK

- src/PolySharp.SourceGenerators/Models/AvailableType.cs
- src/PolySharp.SourceGenerators/PolyfillsGenerator.Execute.cs
- src/PolySharp.SourceGenerators/PolyfillsGenerator.cs
This PR refactors the source generator to stop flowing a `Compilation` object into the incremental pipeline.
cc. @Youssef1313 since we were just talking about this, everything looks good? 😄
> Refactor pipeline to not flow Compilation objects

- PolySharp.sln
- README.md
- src/PolySharp.SourceGenerators/Constants/PolySharpMSBuildProperties.cs
- src/PolySharp.SourceGenerators/Models/GenerationOptions.cs
- src/PolySharp.SourceGenerators/Models/SyntaxFixupType.cs
- src/PolySharp.SourceGenerators/PolySharp.targets
- src/PolySharp.SourceGenerators/PolyfillsGenerator.Execute.cs
- tests/PolySharp.PolySharpUseTypeAliasForUnmanagedCallersOnlyAttribute.Tests/PolySharp.PolySharpUseTypeAliasForUnmanagedCallersOnlyAttribute.Tests.csproj
- tests/PolySharp.PolySharpUseTypeAliasForUnmanagedCallersOnlyAttribute.Tests/UnmanagedCallersOnlyAttributeTests.cs
This PR adds a new "PolySharpUseTypeAliasForUnmanagedCallersOnlyAttribute" option that will alter the generated `[UnmanagedCallersOnly]` attribute type so that (1) it will be generated in the `System.Runtime.InteropServices2` namespace, and (2) a `global using` type alias for it will be generated (so the dummy namespace will never need to be manually imported in a file). This allows methods annotated with the attribute in a multi-targeted project to be allowed to be assigned to a delegate, without Roslyn blocking the operation and demanding the address of the annotated method to be taken instead.
> Add PolySharpUseTypeAliasForUnmanagedCallersOnlyAttribute MSBuild option

- src/PolySharp.SourceGenerators/EmbeddedResources/RuntimeSupported/System.Diagnostics.CodeAnalysis.RequiresDynamicCodeAttribute.cs
- src/PolySharp.SourceGenerators/EmbeddedResources/RuntimeSupported/System.Runtime.CompilerServices.DisableRuntimeMarshallingAttribute.cs
Adds two missing conditional attributes on the last two runtime supported polyfill types.
> Add missing MULTI_TARGETING_SUPPORT_ATTRIBUTES attributes

- Directory.Build.props
- src/Directory.Build.props
- src/PolySharp.Package/PolySharp.Package.msbuildproj
This PR drops the NuGetizer package and just uses vanilla SDK packaging to create the NuGet package.
> Drop NuGetizer from packaging project

- Directory.Build.props
- tests/PolySharp.TypeForwards.Tests/PolySharp.TypeForwards.Tests.csproj
This PR updates all NuGet packages and the shader .props, removing some leftover stuff.
> Update NuGet packages and shader .props

- src/PolySharp.SourceGenerators/PolySharp.targets
This PR adds a warning if packages.config is used in consuming projects.
> Add warning if packages.config is used

- tests/PolySharp.NuGet/PolySharp.NuGet.csproj
- tests/PolySharp.Tests/LanguageFeatures.cs
- tests/PolySharp.Tests/PolySharp.Tests.csproj
- tests/PolySharp.TypeForwards.Tests/PolySharp.TypeForwards.Tests.csproj
- tests/PolySharp.TypeForwards.Tests/TypeForwardTests.cs
This PR removes .NET Core 3.1 from all TFMs, as it's no longer supported.
> Remove .NET Core 3.1 TFMs

- src/PolySharp.SourceGenerators/PolySharp.targets
The current message mentions "shaders", which is irrelevant since PolySharp doesn't process any. Seems to be a leftover from copying the target from ComputeSharp.
> Update Roslyn version error message

- src/PolySharp.SourceGenerators/PolyfillsGenerator.Polyfills.cs
I came across this definition when referencing System.Collections.Immutable in a project that targets .NETstandard 1.3
The attribute is declared internal, so the generated code does not compile.
In the PR I try to reuse the existing check whether "ExcludeFromCodeCoverage" should be removed, in case no public "ExcludeFromCodeCoverage" is found in the compilation
> Remove ExcludeFromCodeCoverage in case the type is not public

- .github/workflows/dotnet.yml
This PR updates the CI script so that it only runs for pushes, or for published PRs from other forks of this repo.
> Skip unnecessary CI runs for PRs from same user

- src/PolySharp.SourceGenerators/EmbeddedResources/RuntimeSupported/System.Diagnostics.CodeAnalysis.RequiresAssemblyFilesAttribute.cs
Most types were already annotated with `ExcludeFromCodeCoverage` but one type was forgotten.
[ReportGenerator](https://www.nuget.org/packages/dotnet-reportgenerator-globaltool) complains about missing source code when generating code coverage reports.
> 2023-09-29T18:28:00: File '/project/PolySharp.SourceGenerators/PolySharp.SourceGenerators.PolyfillsGenerator/System.Diagnostics.CodeAnalysis.RequiresAssemblyFilesAttribute.g.cs' does not exist (any more).
> Exclude RequiresAssemblyFilesAttribute from code coverage

- src/PolySharp.SourceGenerators/EmbeddedResources/RuntimeSupported/System.Runtime.CompilerServices.InlineArrayAttribute.cs
This PR changes the default visibility of the generated `InlineArrayAttribute` from public to internal, to conform with the other generated attributes.
Generated code should only be public when `PolySharpUsePublicAccessibilityForGeneratedTypes` is enabled.
> Fix InlineArrayAttribute visibility

- tests/PolySharp.TypeForwards.Tests/PolySharp.TypeForwards.Tests.csproj
Dependency update, and using metapackage instead of referencing test framework and test adapter individually.
This section should contain the APIs being implemented.
Any additional info that might be useful to resolve the issue.
> Update MSTest to 3.9.1 and use metapackage
